<?php

namespace Tests\Feature;

use App\Models\Link;
use App\Models\User;
use App\Services\ColorConvertorService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\App;
use Tests\TestCase;

class LinkControllerTest extends TestCase
{
    use RefreshDatabase;

    private User $user;

    private Link $link;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->link = Link::factory(['user_id' => $this->user->id])->create();
    }

    /**
     * GET Routes to links
     * @var array|string[]
     */
    public array $routes = [
        'allLinks',
        'createLinkForm',
    ];

    /**
     * User access to all links page
     * @return void
     */
    public function test_access_root_to_links_pages(): void
    {
        $this->actingAs($this->user);

        foreach ($this->routes as $route) {
            $this->get(route($route, ['id' => $this->user->id]))->assertStatus(200);
        }
    }

    /**
     * User unaccess to all links page
     * @return void
     */
    public function test_unaccess_root_to_links_pages(): void
    {
        $this->actingAs($this->user);

        foreach ($this->routes as $route) {
            $this->get(route($route, ['id' => 100]))->assertStatus(404);
        }
    }

    /**
     * test to add new link
     * @return void
     */
    public function test_add_new_link(): void
    {
        $this->actingAs($this->user)->post(route('addLink', ['id' => $this->user->id]), [
            'user_id' => $this->user->id,
            'title' => 'Some random title to link',
            'link' => 'https://vk.com',
            'photo' => UploadedFile::fake()->image('photo.jpg', 500, 500)->size(100),
            'pinned' => false,
            'title_color' => '#000000',
            'background_color' => ColorConvertorService::convertBackgroundColor('#ffffff'),
            'title_color_hex'      => '#000000',
            'background_color_hex' => '#000000',
            'shadow'               => 10,
            'rounded'              => 5,
            'transparency'         => 55,
            'font'                 => 'Inter',
            'font_size'            => 45,
            'text_shadow_color'    => '#ffffff',
            'text_shadow_blur'     => 33,
            'text_shadow_bottom'   => 33,
            'text_shadow_right'    => 33,
            'bold'                 => false,
        ]);

        $this->assertDatabaseHas('links', [
            'title' => 'Some random title to link',
            'link' => 'https://vk.com',
            'user_id' => $this->user->id,
        ]);
    }

    /**
     * test to upd link
     * @return void
     */
    public function test_edit_link(): void
    {
        $this->withoutExceptionHandling();

        $this->actingAs($this->user)->patch(route('editLink', ['id' => $this->user->id, 'link' => $this->link->id]), [
            'user_id' => $this->user->id,
            'title' => 'Some random title to link',
            'link' => 'https://vk.com',
            'photo' => UploadedFile::fake()->image('photo.jpg', 500, 500)->size(100),
            'pinned' => false,
            'title_color' => '#000000',
            'background_color' => ColorConvertorService::convertBackgroundColor('#ffffff'),
            'title_color_hex'      => '#000000',
            'background_color_hex' => '#000000',
            'shadow'               => 10,
            'rounded'              => 5,
            'transparency'         => 55,
            'font'                 => 'Inter',
            'font_size'            => 45,
            'text_shadow_color'    => '#ffffff',
            'text_shadow_blur'     => 33,
            'text_shadow_bottom'   => 33,
            'text_shadow_right'    => 33,
            'bold'                 => false,
        ]);

        $this->assertEquals('Some random title to link', Link::first()->title);
        $this->assertEquals('https://vk.com', Link::first()->link);
        $this->assertEquals($this->user->id, Link::first()->user_id);
    }

    /**
     * test to mass links update
     * @return void
     */
    public function test_mass_edit_links()
    {
        $this->withoutExceptionHandling();

        Link::factory(10, ['user_id' => $this->user->id])->create();

        $this->actingAs($this->user)->patch(route('editAllLink', ['id' => $this->user->id]), [
            'font' => 'Taxoma',
            'font_size' => 1.1,
            'user_id' => $this->user->id,
            'background_color' => ColorConvertorService::convertBackgroundColor('#ffffff'),
        ]);

        $links = Link::all();

        foreach($links as $link) {
            $this->assertEquals('Taxoma', $link->font);
            $this->assertEquals(1.1, $link->font_size);
            $this->assertEquals($this->user->id, $link->user_id);
        }
    }

    /**
     * Drop link test
     * @return void
     */
    public function test_delete_link()
    {
        $this->withoutExceptionHandling();

        $response = $this->actingAs($this->user)->delete(route('delLink', ['id' => $this->user->id, 'link' => $this->link->id]));

        $response->assertStatus(302);

        $this->assertEquals(0, Link::count());
    }

    /**
     * Search link test
     * @return void
     */
    public function test_search_link()
    {
        App::setLocale('RU');

        Link::factory(20, ['user_id' => $this->user->id])->create();

        Link::factory(['user_id' => $this->user->id, 'title' => 'My link'])->create();

        $this->assertCount(22, Link::all());

        $this->assertDatabaseHas('links',['title' => 'My link'])->get(route('searchLink', ['id' => $this->user->id]));
    }
}




